### PR TITLE
Tailwind template

### PR DESCRIPTION
**Pull request by randyridge**
Resolves https://github.com/dominikg/svite/issues/64

### CODE REVIEW

**Comment by dominikg** [comment]
thank you for this PR. I'm not familiar with vs code extensions. are these official tailwind extensions? I'd like to keep svite examples unopinionated and aligned with default setups. So if it is not default, please remove. 

in the same spirit i wonder if lang=postcss should be set as default in svelte-preprocess config over defining it in every svelte file. What do you prefer?

**Comment by randyridge** [comment]
The vscode extension ['official' vscode extension](https://tailwindcss.com/docs/intellisense#app) should probably be included, [the other, headwind](https://marketplace.visualstudio.com/items?itemName=heybourn.headwind) I've found to be pretty common, it normalizes sort order of classes.  That said I'm happy to remove them, though they are just recommendations.

As far as defaulting lang I wasn't aware you could do that... [default lang](https://github.com/sveltejs/svelte-preprocess/issues/184) [another](https://github.com/sveltejs/svelte-preprocess/issues/189)

**Comment by dominikg** [comment]
Thanks for following up. The official tailwind extension looks like a good recommendation to do, actively maintained and on tailwindcss.com. :+1: 
Headwind i'd rather skip. 

The way you included the recommendation does not work though i'm afraid. Removing .vscode from .gitignore would add that directory to the git repository created during `svite create`. The way the svelte recommendation is added is by writing the file during create (similar to how official svelte ts guide does it) and this would overwrite the file you added.
https://github.com/dominikg/svite/blob/f499db42958d824e1986e4a25ac0c7980b3a7a04/bin/svite.js#L284

Currently that function is hardcoded to only include svelte extension, it could be extended to include extensions based on example. Or the way .gitignore and .vscode are handled need to be changed. Keeping .vscode in .gitignore could work, you'd need to force add it then though.
Anyways, result should be 1) tailwind extension suggestion is added only to tailwind examples 2) .gitignore keeps ignore of .vscode 


Regarding default langs:
You can configure them. Unfortunately for now it only works by passing it to autoPreprocessor options. https://github.com/sveltejs/svelte-preprocess/commit/d86122f41a5616b7053dce26d7cf7c58ee025e1d

```js
const sveltePreprocess = require('svelte-preprocess');
module.exports = {
  preprocess: sveltePreprocess({defaults:{style:'postcss',script:'typescript'}}),
};
```

Until a better solution has been found i think  `lang="postcss"`  is fine

**Comment by dominikg** [comment]
didn't leave my head, here's a change in the latest beta regarding postcss lang https://github.com/dominikg/svite/blob/beta/examples/typescript/postcss-tailwind/svelte.config.js

**Comment by randyridge** [comment]
Ok, I didn't spend but a couple minutes and didn't realize you weren't just dropping the templates.

As for preprocess for lang that's fantastic, I was moderately annoyed remembering to type it.

**Pull request closed without merging**
